# Generated by Django 5.1.6 on 2025-03-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='IdeaHUB', max_length=255),
        ),
    ]
